export { default as SubjectDialog } from './Subject/index.vue'
export { default as UserDialog } from './User/index.vue'
export { default as ConfirmDialog } from './Confirm/index.vue'
export { default as ChangePasswordDialog } from './ChangePassword/index.vue'
export { default as ResultDialog } from './Result/index.vue'
export { default as ImageDialog } from './Image/index.vue'